#!/usr/bin/env bash
#  script that displays and I am invincible!!! when receiving a SIGTERM signal
while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM 
done 
